apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: volume1
        secret:
          secretName: test-secret
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: volume1
          mountPath: "/tmp/volume1"
          

