apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
spec:
  capacity:
    storage: 5Gi
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/amorata/kubernetes"
